toggle option menu between decimal or op code instruction
lucasgpulcinelli/goICMCsim pull request #1
Opened 2023-08-30 16:09 UTC by joseCarlosAndrade

oiiiiiii harvssssss

2023-09-01 22:14 UTC, lucasgpulcinelli requested changes
Oi José! As mudanças que você implementou tem uma intenção boa, mas ainda precisam de refinamento na lógica e formatação em si.

2023-09-01 22:14 UTC, lucasgpulcinelli commented on display/menuActions.go
> +	fmt.Println("toggle activated")
Teria como tirar esse print? Não faz sentido ter uma informação de debug na funcionalidade final se as outras ações de input não têm

2023-09-01 22:14 UTC, lucasgpulcinelli commented on display/menuActions.go
> +	updateAllDisplay()
O updateAllDisplay dá um scroll para a instrução atual, por conta disso, caso o usuário esteja numa posição de memória que ele queira visualizar e troque o modo de visualização a posição seria resetada... não teria como só usar o refresh do instruction list diretamente?

2023-09-01 22:14 UTC, lucasgpulcinelli commented on display/widgets.go
> +			// if (viewMode == -1) {
Teria como deletar os comentários de código? Não faz sentido manter isso

2023-09-01 22:14 UTC, lucasgpulcinelli commented on display/widgets.go
> +			mnemonic := icmcSimulator.GetMnemonic(i, viewMode)
Não entendi a mudança de GetMnemonic, não teria como só fazer um if nessa linha para settar o mnemonic baseado no viewMode? Dado que o modo de visualização é pertinente ao sistema de visualização em si (o que faz sentido), por que passar isso ao modo de leitura de mnemonicos de instruções?

2024-02-03 01:58 UTC, lucasgpulcinelli commented
Ping @joseCarlosAndrade

2024-02-03 15:46 UTC, joseCarlosAndrade commented on display/widgets.go
> +			mnemonic := icmcSimulator.GetMnemonic(i, viewMode)
Acredito ter usado uma nomenclatura imcompatível com a lógica nesse caso, mas acredito que o local é plausivel. Pelo meu entendimento da lógica do código, `GetMnemonic` já retorna uma string com a representação da instrução naquela posição. Portanto, implementei a verificação do modo de visualização dentro de `GetMnemonic` para que esta retornasse a string final compatível com o parâmetro de visualizaão, pois no arquivo `widgets.go` (onde o comentário se refere) a informação retornada já é a string final. 

Ou seja, acredito que a passagem desse parametro para o modo de leitura das instruções possa ser necessário para definir o tipo de retorno esperado. Assim, dependendo do parâmetro passado, o retorno pode ser o opcode ou o código bruto.

Ao meu ver, adicionar uma condição dentro deste arquivo pode gerar trabalho redundante, pois a instrução seria transformada já em sua representação string, e, caso a opçãp de `toggle` esteja ativa, teria que retornar novamente ao número bruto da instrução.

2024-02-04 22:34 UTC, lucasgpulcinelli commented on display/widgets.go
> +			mnemonic := icmcSimulator.GetMnemonic(i, viewMode)
Por momento, acredito que podemos manter assim, talvez uma mudança no nome do método seja ideal, mas podemos fazer isso em outro momento.

2024-02-04 22:34 UTC, merged